version: '3.8'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: production-build-base
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - invygomysql
    depends_on:
      - invygomysql
    environment:
      WAIT_HOSTS: invygomysql:3306
  invygomysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: invygomysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: invygo
    ports:
      - '3306:3306'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local